# Generated by Django 3.1 on 2020-10-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Заголовок карточки')),
                ('short_text', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_text', models.TextField(verbose_name='Полное описание(без краткого)')),
            ],
            options={
                'verbose_name': 'Карточка блока подробнее о нас',
                'verbose_name_plural': 'Карточки блока подробнее о нас',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HeaderSlid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_header', models.CharField(max_length=500, verbose_name='Заголовок слайда')),
                ('slide_text', models.TextField(verbose_name='Текст слайда')),
                ('page', models.CharField(choices=[('researches', 'Исследования'), ('cooperation', 'Сотрудничество'), ('home', 'Главная страница'), ('questions', 'Как сдать анализы')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото отобржаемое на слайдере')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки(если есть)')),
                ('button_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка кнопки')),
                ('link_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст ссылки(если есть)')),
                ('link_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='URL ссылки')),
            ],
            options={
                'verbose_name': 'Слайд хедера',
                'verbose_name_plural': 'Слайды хедера',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок новости')),
                ('img', models.ImageField(upload_to='img', verbose_name='Картинка новости')),
                ('date', models.DateField(verbose_name='Дата новости')),
                ('link', models.CharField(max_length=256, verbose_name='Ссылка на новость')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название партнера')),
                ('img', models.ImageField(upload_to='img', verbose_name='Картинка логотипа')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('show_home', models.BooleanField(verbose_name='Отображение на главной странице')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос/ответ',
                'verbose_name_plural': 'Часто задаваемые вопросы/ответы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResearchMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название метода')),
                ('period', models.IntegerField(verbose_name='Срок исследования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена исследования')),
            ],
            options={
                'verbose_name': 'Метод исследования',
                'verbose_name_plural': 'Методы исследования',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResearchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название вида исследования')),
                ('methods', models.ManyToManyField(to='main_app.ResearchMethod', verbose_name='Методы исследования')),
            ],
            options={
                'verbose_name': 'Вид исследования',
                'verbose_name_plural': 'Виды исследования',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название исследования')),
                ('types', models.ManyToManyField(to='main_app.ResearchType', verbose_name='Входящие в него виды исследвания')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
