# Generated by Django 3.1 on 2020-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default='pass', verbose_name='Текст новости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('cooperation', 'Сотрудничество'), ('home', 'Главная страница'), ('questions', 'Как сдать анализы'), ('researches', 'Исследования')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
