# Generated by Django 3.1 on 2020-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('home', 'Главная страница'), ('questions', 'Как сдать анализы'), ('cooperation', 'Сотрудничество'), ('researches', 'Исследования')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
