# Generated by Django 3.1 on 2020-10-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201022_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='ico',
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('cooperation', 'Сотрудничество'), ('home', 'Главная страница'), ('questions', 'Как сдать анализы'), ('researches', 'Исследования')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
