# Generated by Django 3.1 on 2020-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201022_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='ico',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='img', verbose_name='Иконка данного блока(jpg, svg, png)'),
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('questions', 'Как сдать анализы'), ('cooperation', 'Сотрудничество'), ('home', 'Главная страница'), ('researches', 'Исследования')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
