# Generated by Django 3.1 on 2020-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201022_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('questions', 'Как сдать анализы'), ('home', 'Главная страница'), ('cooperation', 'Сотрудничество'), ('researches', 'Исследования')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
