# Generated by Django 3.1 on 2020-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201111_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchmethod',
            name='about',
        ),
        migrations.RemoveField(
            model_name='researchmethod',
            name='decryption',
        ),
        migrations.RemoveField(
            model_name='researchmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='researchmethod',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='researchmethod',
            name='slug',
        ),
        migrations.AddField(
            model_name='researchtype',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Что исследуется'),
        ),
        migrations.AddField(
            model_name='researchtype',
            name='decryption',
            field=models.TextField(blank=True, null=True, verbose_name='Расшифровка'),
        ),
        migrations.AddField(
            model_name='researchtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание исследования'),
        ),
        migrations.AddField(
            model_name='researchtype',
            name='preparation',
            field=models.TextField(blank=True, null=True, verbose_name='Подготовка'),
        ),
        migrations.AddField(
            model_name='researchtype',
            name='slug',
            field=models.SlugField(default='ok', verbose_name='Ссылка вида исследования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('home', 'Главная страница'), ('cooperation', 'Сотрудничество'), ('questions', 'Как сдать анализы'), ('researches', 'Исследования')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
