# Generated by Django 3.1 on 2020-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201111_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('researches', 'Исследования'), ('home', 'Главная страница'), ('questions', 'Как сдать анализы'), ('cooperation', 'Сотрудничество')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
