# Generated by Django 3.1 on 2020-12-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20201121_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='full_text',
            field=models.TextField(default='something', verbose_name='Полный текст новости(короткий писать не надо)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='short_text',
            field=models.TextField(default='short_text', verbose_name='Короткий текст новости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('cooperation', 'Сотрудничество'), ('home', 'Главная страница'), ('researches', 'Исследования'), ('questions', 'Как сдать анализы')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
