# Generated by Django 3.1 on 2021-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210306_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
            ],
            options={
                'verbose_name': 'Почта для рассылки',
                'verbose_name_plural': 'Почты для рассылки',
            },
        ),
        migrations.AlterField(
            model_name='headerslid',
            name='page',
            field=models.CharField(choices=[('home', 'Главная страница'), ('about', 'О нас'), ('cooperation', 'Сотрудничество'), ('researches', 'Исследования'), ('news', 'Новости'), ('questions', 'Как сдать анализы')], default='home', max_length=50, verbose_name='Страница на которой отображать данный слайд'),
        ),
    ]
